language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import python-dateutil gitpython Pillow disqus-python
addons:
  apt:
    packages:
    - asciidoc
    - source-highlight
script:
- make publish github
env:
  global:
  - GH_USER=jduncan-rva
  - GH_REPO=blog
  - GH_BRANCH=gh-pages
  - secure: HCnu0i8ZqDP3SRbWgwfCuIYfijt/LVVNHwlNw1Ju1zYiK0zGxy96G0EHGJwlFGXi/JIP98/DE1y77I5dF0vgzNcMC+adI7EoeWaL7qaNR3PK/uZJPG+VcQ5myMe6Fo0seWG9QRK+LD7Goz2pdDizDYsEplDibI5tq4m/pm7FDb/PgEwtOMreHIe2RJc3gTSo1+D5+7XYMLatoQuYx6GMfVo93IvxY/Y5LdJhORlmJSfuIVkvwnbhnNR5PRtbTnBmyaQSpQ6st/rIHKdnq01P3r2cMUB/qh64pxb/8cFpYNgt+flvthgjfLac9KcpmIJ8kjrt0T3PGs5/Lx6ws96ppy8V2QsRNTuQNpuDITGXd4cwwE/5eTL8PnwcCJsnslNwYoL3oXPOWTwccKjIwb6eDVLBm/j2nSwMSsaIDzvHKmOAgq2k9hdD8M3HM8WX83GO+2NMtqc4+Q2EYoAEKb5Yc7ASV7MC2+PKlZwk7Z+rLbuRMtyupQ3n9AOdcOlvNqXUfEotfeMpeRVSS6ilna9f+Pj2gEJwJKKz5Son9i0C/Rd9ORI+2q046G2d5Lr0bIaK8FI2fOhJX8CMiWGY09eDgkeKeIuXkMSG/nqRjWt8c5h332g8uscKkCXfrknZKLg9rfnTT0MXQQQ0x+/A8VoEC4AU4tE30YEzTzMvhSuc36g=
